### PR TITLE
Use <em> and <strong> for emphasis

### PR DESCRIPTION
**Pull request by RubenVerborgh**
RASH uses the wrong elements for emphasis:
- HTML5 [defines the `<i>` element](https://www.w3.org/TR/html5/text-level-semantics.html#the-i-element) to “[represent] a span of text in an alternate voice or mood, or otherwise offset from the normal prose in a manner indicating a different quality of text, such as a taxonomic designation, a technical term, an idiomatic phrase from another language, transliteration, a thought, or a ship name in Western texts.”
- HTML5 [defines the `<b>` element](https://www.w3.org/TR/html5/text-level-semantics.html#the-b-element) to “[represent] a span of text to which attention is being drawn for utilitarian purposes without conveying any extra importance and with no implication of an alternate voice or mood, such as key words in a document abstract, product names in a review, actionable words in interactive text-driven software, or an article lede.”

This pull request introduces the correct elements with the semantics intended by RASH, which is `<em>` for emphasis and `<strong>` for strong emphasis.

With this pull request RASH becomes compatible with HTML5 with regard to emphasis.

### CODE REVIEW

**Comment by nemanjavuk** [comment]
+1

**Comment by RubenVerborgh** [comment]
Awesome, thanks :smile:

**Comment by sideshowbarker** [comment]
This change is a mistake based on a common misunderstanding about HTML and it’s disappointing to see it getting enshrined in RASH.

**Comment by RubenVerborgh** [comment]
@sideshowbarker What “common misunderstanding” do you mean? Please clarify why `<i>` and `<b>` would be more appropriate for emphasis and strong emphasis than `<em>` and `<strong>` (and don't forget to back that up with references to the HTML specification).

**Comment by sideshowbarker** [comment]
@RubenVerborgh I’ll pass.

**Comment by RubenVerborgh** [comment]
@sideshowbarker Given your lack of arguments, I guess we can safely say the HTML specification proves this change correct. Here's the specification of [`<i>`](https://www.w3.org/TR/html5/text-level-semantics.html#the-i-element), [`<b>`](https://www.w3.org/TR/html5/text-level-semantics.html#the-b-element), [`<em>`](https://www.w3.org/TR/html5/text-level-semantics.html#the-em-element), and [`<strong>`](https://www.w3.org/TR/html5/text-level-semantics.html#the-strong-element) to take away your latest doubts.

**Pull request merged**
